-- Phần A. Phân tích và viết các lệnh để xây dựng cơ sở dữ liệu dựa vào mô tả phía trên
CREATE DATABASE java23_company;

CREATE TABLE POSITION (
    POSITION_ID INT AUTO_INCREMENT PRIMARY KEY,
    POSITION_NAME NVARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    DEPARTMENT_NAME NVARCHAR(100) UNIQUE NOT NULL ,
    NUMBER_OF_EMPLOYEES INT NOT NULL,
    -- EMPLOYEE_ID INT NOT NULL,
    INAUGURATION_DAY DATE NOT NULL
    -- FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

ALTER TABLE DEPARTMENT
ADD COLUMN EMPLOYEE_ID INT NULL;

ALTER TABLE DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_EMPLOYEE
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID);


CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
    EMPLOYEE_NAME NVARCHAR(100) UNIQUE NOT NULL,
    ADDRESS NVARCHAR(255) NOT NULL,
    SALARY DECIMAL(10,2) NOT NULL,
    GENDER BIT(1) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    JOINING_COMPANY_DATE DATE NOT NULL,
    DEPARTMENT_ID INT NOT NULL,
    POSITION_ID INT NOT NULL,
    REF_EMPLOYEE_ID INT,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID),
    FOREIGN KEY (POSITION_ID) REFERENCES POSITION (POSITION_ID),
    FOREIGN KEY (REF_EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

CREATE TABLE POSITION_DETAIL (
	POSITION_ID INT NOT NULL,
    EMPLOYEE_ID INT NOT NULL,
    PRIMARY KEY (POSITION_ID, EMPLOYEE_ID),
    FOREIGN KEY (POSITION_ID) REFERENCES POSITION (POSITION_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID)
);

CREATE TABLE PROJECT (
    PROJECT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PROJECT_NAME NVARCHAR(100) UNIQUE NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    REVENUE DECIMAL(10,2) NOT NULL,
    EMPLOYEE_ID INT NOT NULL,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

CREATE TABLE PROJECT_DETAIL (
    PROJECT_DETAIL_ID INT AUTO_INCREMENT PRIMARY KEY,
    PROJECT_ID INT NOT NULL,
    EMPLOYEE_ID INT NOT NULL,
    WORKING_TIME DATE NOT NULL,
    WORKING_HOURS INT NOT NULL,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

CREATE TABLE UPDATE_PROJECT (
	UPDATE_PROJECT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PROJECT_DETAIL_ID INT NOT NULL,
    WORKING_TIME_ADDED INT NOT NULL,
    UPDATE_TIME DATE NOT NULL,
    FOREIGN KEY (PROJECT_DETAIL_ID) REFERENCES PROJECT_DETAIL(PROJECT_DETAIL_ID)
);




