CREATE DATABASE lesson18_hongtrung;
USE lesson18_hongtrung;


CREATE TABLE T01_CLASS (
    C01_CLASS_ID INT PRIMARY KEY AUTO_INCREMENT,
    C01_CLASS_NAME VARCHAR(100) NOT NULL,
    C01_CLASS_TEACHER VARCHAR(100)
);

CREATE TABLE T02_STUDENT (
    C02_STUDENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    C02_STUDENT_NAME VARCHAR(100) NOT NULL,
    C02_STUDENT_GENDER ENUM('Male','Female') NOT NULL,
    C02_CLASS_ID INT,
    CONSTRAINT FK_T01_T02 FOREIGN KEY (C02_CLASS_ID) REFERENCES T01_CLASS(C01_CLASS_ID)
);

CREATE TABLE T03_RESULT (
    C03_STUDENT_ID INT,
    C03_SUBJECT VARCHAR(50),
    C03_SCORE DECIMAL(4,2),
    PRIMARY KEY (C03_STUDENT_ID, C03_SUBJECT),
    CONSTRAINT FK_T03_T02 FOREIGN KEY (C03_STUDENT_ID) REFERENCES T02_STUDENT(C02_STUDENT_ID)
);

INSERT INTO T01_CLASS (C01_CLASS_NAME, C01_CLASS_TEACHER)
VALUES
('12A', 'Ho Cong Trung'),
('12B', 'Dang Tu Anh'),
('12C', 'Nguyen Van Tam');

INSERT INTO T02_STUDENT (C02_STUDENT_NAME, C02_STUDENT_GENDER, C02_CLASS_ID)
VALUES
('Dinh Thi Ngoc', 'Female', 2),
('Nguyen Thanh Hung', 'Male', 1),
('Tran Mai Hoa', 'Female', 2),
('Doan Quang Vinh', 'Male', 1),
('Cao Anh Dao', 'Female', 3),
('Tran Kim Tuyen', 'Male', 3);


INSERT INTO T02_STUDENT (C02_STUDENT_NAME, C02_STUDENT_GENDER, C02_CLASS_ID)
VALUES
('Nguyen Hong Trung', 'Male', 2),
('Nguyen Van Hung', 'Male', 1),
('Tran Mai', 'Female', 2);

INSERT INTO T03_RESULT (C03_STUDENT_ID, C03_SUBJECT, C03_SCORE)
VALUES
(1, 'Math', 8.0),
(1, 'Literature', 7.0),
(2, 'History', 9.5),
(4, 'Math', 6.8),
(5, 'Literature', 4.9),
(6, 'History', 8.2),
(7, 'Math', 9.8),  
(8, 'Literature', 7.2), 
(9, 'History', 8.8);

INSERT INTO T03_RESULT (C03_STUDENT_ID, C03_SUBJECT, C03_SCORE)
VALUES
(9, 'Math', 9.0),
(7, 'Literature', 8.0);
-- PK của table Result là student_id và subject vì nếu pk chỉ là student id thì mỗi học sinh 
-- sẽ chỉ có một bản ghi - học một môn -  trên result (trong khi đáng lẽ một học sinh phải học được nhiều môn)
-- nếu pk chỉ là subject thì mỗi môn chỉ có - một bản ghi - một học sinh 
-- --> chọn pk là (student_id, subject), mỗi học sinh chỉ có một keetss quả cho mỗi môn học

-- LIST NAME, GENDER, TEACHER NAME OF ALL STUDNETS
SELECT T02.C02_STUDENT_NAME, T02.C02_STUDENT_GENDER , T01.C01_CLASS_TEACHER FROM T02_STUDENT T02 
JOIN T01_CLASS T01 ON T02.C02_CLASS_ID = T01.C01_CLASS_ID;

-- LIST TEACHER NAME, COUNT NUMBER OF STUDNETS CLASS 12C
SELECT T01.C01_CLASS_TEACHER, COUNT(T02.C02_STUDENT_ID) AS STUDENT_COUNT
FROM T02_STUDENT T02 
JOIN T01_CLASS T01 ON T02.C02_CLASS_ID = T01.C01_CLASS_ID
WHERE T01.C01_CLASS_NAME = '12C'
GROUP BY T01.C01_CLASS_TEACHER;

-- LIST CLASS NAME, NUMBER OF STUDNETS WHO MATH SCORE & LITERATURE SCORE >= 8
SELECT T01.C01_CLASS_NAME, COUNT(T02.C02_STUDENT_ID) AS STUDENT_COUNT
FROM T02_STUDENT T02 
JOIN T01_CLASS T01 ON T02.C02_CLASS_ID = T01.C01_CLASS_ID 
WHERE EXISTS (
	SELECT 1
	FROM T03_RESULT T03_1
    WHERE T03_1.C03_STUDENT_ID = T02.C02_STUDENT_ID
		AND T03_1.C03_SUBJECT = 'Math'
		AND T03_1.C03_SCORE >= 8
    )
  AND EXISTS (
	SELECT 1
    FROM T03_RESULT T03_2
    WHERE T03_2.C03_STUDENT_ID = T02.C02_STUDENT_ID
		AND T03_2.C03_SUBJECT = 'Literature'
		AND T03_2.C03_SCORE >= 8
    )
GROUP BY T01.C01_CLASS_NAME;

