-- java23-shopping dbp 04.sql
-- T14_TITLE, T08_EMPLOYEE, T07_CUSTOMER
USE java23_shopping;
CREATE TABLE T14_TITLE (
	C14_TITLE_ID INT AUTO_INCREMENT,
	C14_TITLE_NAME VARCHAR(225) NOT NULL,
    PRIMARY KEY (C14_TITLE_ID),
	CONSTRAINT UNQ_C14_TITLE_NAME UNIQUE T14_TITLE(C14_TITLE_NAME)
);
CREATE TABLE T08_EMPLOYEE(
	C08_EMPLOYEE_ID INT AUTO_INCREMENT,
	C08_EMPLOYEE_NAME VARCHAR(225) NOT NULL,
	C08_EMPLOYEE_PHONE VARCHAR(11) NOT NULL,
	C08_EMPLOYEE_EMAIL VARCHAR(50) NOT NULL,
	C08_EMPLOYEE_GENDER BIT(1) NOT NULL,
	C08_EMPLOYEE_DOB DATE NOT NULL,
	C08_TITLE_ID INT NOT NULL,
	C08_ACCOUNT_ID INT NOT NULL,
    PRIMARY KEY (C08_EMPLOYEE_ID),
    CONSTRAINT UNQ_T08_NAME_PHONE_EMAIL  UNIQUE T08_EMPLOYEE(C08_EMPLOYEE_NAME,C08_EMPLOYEE_PHONE,C08_EMPLOYEE_EMAIL),
    CONSTRAINT FK_T08_T14 FOREIGN KEY (C08_TITLE_ID) REFERENCES T14_TITLE(C14_TITLE_ID),
    CONSTRAINT FK_T08_T09 FOREIGN KEY ( C08_ACCOUNT_ID) REFERENCES T09_ACCOUNT(C09_ACCOUNT_ID)
);
CREATE TABLE T07_CUSTOMER(
	C07_CUSTOMER_ID INT AUTO_INCREMENT,
	C07_CUSTOMER_NAME VARCHAR(225) NOT NULL,
	C07_CUSTOMER_PHONE VARCHAR(11) NOT NULL,
	C07_CUSTOMER_EMAIL VARCHAR(50) NOT NULL,
	C07_CUSTOMER_GENDER BIT(1) NOT NULL,
	C07_CUSTOMER_DOB DATE NOT NULL,
	C07_CUSTOMER_ADDRESS VARCHAR(225) NOT NULL,
	C07_ACCOUNT_ID INT NOT NULL,
    PRIMARY KEY(C07_CUSTOMER_ID),
	CONSTRAINT UNQ_T07_NAME_PHONE_EMAIL  UNIQUE T07_CUSTOMER(C07_CUSTOMER_NAME,C07_CUSTOMER_PHONE,C07_CUSTOMER_EMAIL),
	CONSTRAINT FK_T07_T09 FOREIGN KEY (C07_ACCOUNT_ID) REFERENCES T09_ACCOUNT(C09_ACCOUNT_ID)
);
