-- java23-shopping dbp 06.sql
-- T11_ORDER_STATUS, T12_ORDER_STATUS_DETAIL
CREATE TABLE T11_ORDER_STATUS (
	C11_ORDER_STATUS_ID INT AUTO_INCREMENT,
	C11_ORDER_STATUS_DESC VARCHAR(50) NOT NULL,
    PRIMARY KEY(C11_ORDER_STATUS_ID)
);
CREATE TABLE T12_ORDER_STATUS_DETAIL (
	C12_ORDER_ID INT AUTO_INCREMENT,
	C12_ORDER_STATUS_ID INT NOT NULL,
	C12_EMPLOYEE_ID INT NOT NULL,
	C12_LAST_UPDATED VARCHAR(50),
	PRIMARY KEY(C12_ORDER_ID),
    CONSTRAINT FK_T12_T11 FOREIGN KEY (C12_ORDER_STATUS_ID) REFERENCES T11_ORDER_STATUS(C11_ORDER_STATUS_ID),
	CONSTRAINT FK_T12_T08 FOREIGN KEY (C12_EMPLOYEE_ID) REFERENCES T08_EMPLOYEE(C08_EMPLOYEE_ID)
);
