-- java23-shopping dbp 03.sql
-- T09_ACCOUNT, T10_ROLE
USE java23_shopping;
CREATE TABLE T09_ACCOUNT (
	C09_ACCOUNT_ID INT AUTO_INCREMENT,
	C09_USERNAME VARCHAR(225) NOT NULL,
	C09_PASSWORD VARCHAR(225) NOT NULL,
	C09_ACCOUNT_STATUS VARCHAR(50),
	C09_ROLE_ID INT NOT NULL,
	PRIMARY KEY (C09_ACCOUNT_ID),
    CONSTRAINT UNQ_C09_USERNAME_PASSWORD UNIQUE T09_ACCOUNT(C09_USERNAME,C09_PASSWORD),
	CONSTRAINT FK_T09_T10 FOREIGN KEY (C09_ROLE_ID) REFERENCES T10_ROLE(C10_ROLE_ID)
);
CREATE TABLE T10_ROLE(
	C10_ROLE_ID INT AUTO_INCREMENT,
    C10_ROLE_NAME VARCHAR(225) NOT NULL,
    PRIMARY KEY(C10_ROLE_ID),
    CONSTRAINT UNQ_C10_ROLE_NAME UNIQUE T10_ROLE(C10_ROLE_NAME)
);