-- java23-shopping dbp 01.sql
-- T04_ITEM_GROUP
USE java23_shopping;

CREATE TABLE T04_ITEM_GROUP(
	C04_ITEM_GROUP_ID INT AUTO_INCREMENT PRIMARY KEY,
    C04_ITEM_GROUP_NAME VARCHAR(225) NOT NULL,
    CONSTRAINT UNQ_C02_ITEM_GROUP_NAME UNIQUE(C04_ITEM_GROUP_NAME)
);