
CREATE TABLE T01_DEPARTMENT (
    C01_DEPARTMENT_ID VARCHAR(10) PRIMARY KEY,
    C01_DEPARTMENT_NAME NVARCHAR(100) UNIQUE NOT NULL ,
    C01_NUMBER_OF_EMPLOYEES INT NOT NULL,
    C01_EMPLOYEE_ID VARCHAR(10) NOT NULL,
    C01_INAUGURATION_DAY DATE NOT NULL,
    FOREIGN KEY (C01_EMPLOYEE_ID) REFERENCES T02_EMPLOYEE(C02_EMPLOYEE_ID)
);


CREATE TABLE TO2_EMPLOYEE (
    C02_EMPLOYEE_ID VARCHAR(10) PRIMARY KEY,
    C02_EMPLOYEE_NAME NVARCHAR(100) UNIQUE NOT NULL,
    C02_ADDRESS NVARCHAR(255) NOT NULL,
    C02_SALARY DECIMAL(10,2) NOT NULL,
    C02_GENDER BIT(1) NOT NULL,
    C02_DATE_OF_BIRTH DATE NOT NULL,
    C02_JOINING_COMPANY_DATE DATE NOT NULL,
    C02_DEPARTMENT_ID VARCHAR(10) NOT NULL,
    C02_STATUS_ID VARCHAR(10) NOT NULL,
    C02_REF_EMPLOYEE_ID VARCHAR(10),
  --  FOREIGN KEY (C02_DEPARTMENT_ID) REFERENCES T01_DEPARTMENT(C01_DEPARTMENT_ID),
    constraint FK_T02_T04_STATUS foreign key  (C02_STATUS_ID) REFERENCES T04_STATUS (c04_status_id)
   -- FOREIGN KEY (C02_REF_EMPLOYEE_ID) REFERENCES T01_EMPLOYEE(C01_EMPLOYEE_ID)
);


CREATE TABLE TO3_PROJECT (
    C03_PROJECT_ID VARCHAR(10) PRIMARY KEY,
   C03_PROJECT_NAME NVARCHAR(100) UNIQUE NOT NULL,
    C03_START_DATE DATE NOT NULL,
    C03_END_DATE DATE NOT NULL,
    C03_REVENUE DECIMAL(15,2) NOT NULL,
    C03_SUPERVISOR_EMPLOYEE_ID VARCHAR(10) NOT NULL,
    FOREIGN KEY (C03_SUPERVISOR_EMPLOYEE_ID) REFERENCES T01_EMPLOYEE(C01_EMPLOYEE_ID)
);

CREATE TABLE T04_STATUS (
   c04_status_id int auto_increment,
   c04_status_name varchar(255),
   primary key (c04_status_id)
);

CREATE TABLE T05_STATUS_DETAIL (
   c05_status_id int auto_increment,
   c05_employ_id int auto_increment,
   primary key (C05_status_id, c05_employ_id),
   FOREIGN KEY (C05_STATUS_ID) REFERENCES T02_EMPLOYEE(C02_STATUS_ID),
    FOREIGN KEY (C05_employ_id) REFERENCES T02_EMPLOYEE(C02_EMPLOYEE_ID)

);

create table T06_RECORD (
  c06_employ_time int,
  co6_project_id int
  );