CREATE DATABASE lesson18_exam CHAR SET utf8mb4;

USE lesson18_exam;

-- DDL

CREATE TABLE T01_CLASS (
    C01_CLASS_ID INT AUTO_INCREMENT,
    C01_CLASS_NAME VARCHAR(100) NOT NULL,
    C01_TEACHER VARCHAR(100) NOT NULL,
    PRIMARY KEY (C01_CLASS_ID)
);

CREATE TABLE T02_STUDENT (
    C02_STUDENT_ID INT AUTO_INCREMENT,
    C02_NAME VARCHAR(100) NOT NULL,
    C02_GENDER ENUM('Male', 'Female') NOT NULL,
    C02_CLASS_ID INT,
    PRIMARY KEY (C02_STUDENT_ID),
    CONSTRAINT FK_T02_T01 FOREIGN KEY (C02_CLASS_ID) REFERENCES T01_CLASS(C01_CLASS_ID)
);

CREATE TABLE T03_RESULT (
    C03_STUDENT_ID INT,
    C03_SUBJECT VARCHAR(100) NOT NULL,
    C03_SCORE DECIMAL(2,1) NOT NULL,
    PRIMARY KEY (C03_STUDENT_ID, C03_SUBJECT),
    CONSTRAINT FK_T03_T02 FOREIGN KEY (C03_STUDENT_ID) REFERENCES T02_STUDENT(C02_STUDENT_ID)
);

-- Khóa chính của bảng result là cột C03_STUDENT_ID và cột C03_SUBJECT vì mỗi học sinh chỉ có 1 điểm số cho 1 môn học

-- DML
INSERT INTO T01_CLASS (C01_CLASS_NAME, C01_TEACHER)
VALUES ('12A', 'Ho Cong Trung'),
	   ('12B', 'Dang Tu Anh'),
       ('12C', 'Nguyen Van Tam');
SELECT * FROM T01_CLASS;

INSERT INTO T02_STUDENT (C02_NAME, C02_GENDER, C02_CLASS_ID)
VALUES ('Dinh Thi Ngoc', 'Female', 2),
	   ('Nguyen Thanh Hung', 'Male', 1),
       ('Tran Mai Hoa', 'Female', 2),
       ('Doan Quang Vinh', 'Male', 1),
       ('Cao Anh Dao', 'Female', 3),
       ('Tran Kim Tuyen', 'Male', 3),
       ('Vo Minh Chau', 'Female', 2),
	   ('Phan Quoc Huy', 'Male', 1),
	   ('Bui Thi Thanh', 'Female', 3);

INSERT INTO T03_RESULT (C03_STUDENT_ID, C03_SUBJECT, C03_SCORE)
VALUES (1, 'Math', 8.0),
	   (2, 'Literature', 7.0),
       (3, 'History', 9.5),
       (4, 'Math', 6.8),
	   (5, 'Literature', 4.9),
       (6, 'History', 8.2),
       (7, 'Math', 9.8),
	   (8, 'Literature', 7.2),
       (9, 'History', 8.8);

-- Quẻies

SELECT t02.C02_NAME AS STUDENT_NAME,
	   t02.C02_GENDER AS GEMDER,
       t01.C01_TEACHER AS TEACHER_NAME
  FROM T02_STUDENT t02
  JOIN T01_CLASS t01 ON t02.C02_CLASS_ID = t01.C01_CLASS_ID;

SELECT t01.C01_TEACHER AS TEACHER_NAME,
 COUNT(t02.C02_STUDENT_ID) AS TOTAL_STUDENT
  FROM T01_CLASS t01
  JOIN T02_STUDENT t02 ON t01.C01_CLASS_ID = t02.C02_CLASS_ID
 WHERE t01.C01_CLASS_NAME = '12C'
 GROUP BY t01.C01_TEACHER;
 
SELECT t01.C01_CLASS_NAME AS CLASS_NAME,
	   t03.C03_SUBJECT AS SUBJECT,
 COUNT(DISTINCT T02.C02_STUDENT_ID) AS GOOD_STUDEMT_COUNT
  FROM T03_RESULT t03
  JOIN T02_STUDENT t02 ON t03.C03_STUDENT_ID = t02.C02_STUDENT_ID
  JOIN T01_CLASS t01 ON t02.C02_CLASS_ID = t01.C01_CLASS_ID
 WHERE t03.C03_SUBJECT IN ('Math', 'Literature') AND t03.C03_SCORE >= 8
 GROUP BY t01.C01_CLASS_NAME, t03.C03_SUBJECT;

SELECT *
  FROM T02_STUDENT
 ORDER BY C02_CLASS_ID;

