-- java23-shopping dbp 02.sql
-- T01_ITEM, T02_SIZE, T03_ITEM_DETAIL, T05_GALLERY

DROP TABLE IF EXISTS T01_ITEM;
CREATE TABLE T01_ITEM (
	C01_ITEM_ID INT AUTO_INCREMENT,
	C01_ITEM_NAME VARCHAR(255) NOT NULL,
	C01_ITEM_GROUP_ID INT NOT NULL,
    PRIMARY KEY (C01_ITEM_ID),
    CONSTRAINT FK_T01_T04 FOREIGN KEY (C01_ITEM_GROUP_ID) REFERENCES T04_ITEM_GROUP(C04_ITEM_GROUP_ID),
    CONSTRAINT UNQ_C01_ITEM_NAME UNIQUE(C01_ITEM_NAME)
);

DROP TABLE IF EXISTS T02_SIZE;
CREATE TABLE T02_SIZE(
	C02_SIZE_ID INT AUTO_INCREMENT,
	C02_SIZE_NAME VARCHAR(5) NOT NULL,
	C02_GENDER BIT(1) NOT NULL,
	C02_SIZE_DESC TEXT NOT NULL,
    PRIMARY KEY (C02_SIZE_ID),
    CONSTRAINT UNQ_C02_SIZE_NAME_GENDER UNIQUE(C02_SIZE_NAME, C02_GENDER),
    CONSTRAINT C02_SIZE_NAME_CHECK CHECK (C02_SIZE_NAME IN ('S', 'M', 'L', 'XL', 'XXL', 'XXXL'))
);

DROP TABLE IF EXISTS T03_ITEM_DETAIL;
CREATE TABLE T03_ITEM_DETAIL (
	C03_ITEM_DETAIL_ID INT AUTO_INCREMENT,
	C03_ITEM_ID INT NOT NULL,
	C03_SIZE_ID INT NOT NULL,
	C03_COLOR VARCHAR(50) NOT NULL,
	C03_SALES_PRICE FLOAT, -- hàng mới mua, chưa xác định giá bán
	C03_AMOUNT INT NOT NULL DEFAULT (0),
    PRIMARY KEY (C03_ITEM_DETAIL_ID),
    CONSTRAINT FK_T03_T01 FOREIGN KEY (C03_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID),
    CONSTRAINT FK_T03_T02 FOREIGN KEY (C03_SIZE_ID) REFERENCES T02_SIZE(C02_SIZE_ID),
    CONSTRAINT UNQ_C02_ITEM_SIZE_COLOR UNIQUE(C03_ITEM_ID, C03_SIZE_ID, C03_COLOR)
);

CREATE TABLE T05_GALLERY(
	C05_ITEM_ID INT,
	C05_COLOR VARCHAR(50),
	C05_IMAGE VARCHAR(255) NOT NULL,
    PRIMARY KEY (C05_ITEM_ID, C05_COLOR),
    CONSTRAINT UNQ_C05_IMAGE UNIQUE(C05_IMAGE)
);

ALTER TABLE T05_GALLERY
ADD CONSTRAINT FK_T05_T01 FOREIGN KEY (C05_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID);

-- need drop tables