-- -- T09_ACCOUNT,	T10_ROLE

CREATE TABLE T10_ROLE (
	C10_ROLE_ID INT AUTO_INCREMENT PRIMARY KEY,
	C10_ROLE_NAME BIT(3) NOT NULL
);

CREATE TABLE T09_ACCOUNT (
	C09_ACCOUNT_ID INT AUTO_INCREMENT PRIMARY KEY,
	C09_USERNAME VARCHAR(30) NOT NULL,
	C09_PASSWORD VARCHAR(30) NOT NULL,
	C09_ACCOUNT_STATUS BIT(2) NOT NULL,
	C09_ROLE_ID INT NOT NULL,
    CONSTRAINT FK_T09_T10 FOREIGN KEY (C09_ROLE_ID) REFERENCES T10_ROLE (C10_ROLE_ID)
);