-- java23-shopping dbp 04.sql
-- T14_TITLE, T08_EMPLOYEE, T07_CUSTOMER
USE java23_shopping;
CREATE	TABLE T14_TITLE(
	C14_TITLE_ID INT AUTO_INCREMENT,
    C14_TITLE_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY(C14_TITLE_ID),
    CONSTRAINT UNQ_C14_TITLE_NAME UNIQUE(C14_TITLE_NAME)
);
CREATE TABLE T08_EMPLOYEE(
	C08_EMPLOYEE_ID INT AUTO_INCREMENT,
    C08_EMPLOYEE_NAME VARCHAR(255) NOT NULL,
    C08_EMPLOYEE_PHONE VARCHAR(255) NOT NULL,
    C08_EMPLOYEE_EMAIL VARCHAR (255) NOT NULL,
    C08_EMPLOYEE_GENDER BIT(1) NOT NULL,
    C08_EMPLOYEE_DOB VARCHAR(255)NOT NULL ,
	C08_TITLE_ID INT NOT NULL ,
    C08_ACCOUNT_ID INT NOT NULL,
    PRIMARY KEY(C08_EMPLOYEE_ID),
    CONSTRAINT FK_08_09 FOREIGN KEY (C08_ACCOUNT_ID) REFERENCES T09_ACCOUNT(C09_ACCOUNT_ID)
);
CREATE TABLE T07_CUSTOMER(
	C07_CUSTOMER_ID INT AUTO_INCREMENT,
    C07_CUSTOMER_NAME VARCHAR(255) NOT NULL,
    C07_CUSTOMER_PHONE VARCHAR(255) NOT NULL,
    C07_CUSTOMER_EMAIL VARCHAR(255) NOT NULL,
    C07_CUSTOMER_GENDER VARCHAR(255) NOT NULL,
    C07_CUSTOMER_DOB VARCHAR(255) NOT NULL,
    C07_CUSTOMER_ADDRESS VARCHAR(255) NOT NULL,
    C07_ACCOUNT_ID INT NOT NULL,
    PRIMARY KEY (C07_CUSTOMER_ID),
    CONSTRAINT FK_07_09 FOREIGN KEY (C07_ACCOUNT_ID) REFERENCES T09_ACCOUNT(C09_ACCOUNT_ID)
);