CREATE TABLE T14_TITLE (
    C14_TITLE_ID INT AUTO_INCREMENT,
    C14_TITLE_NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (C14_TITLE_ID),
    CONSTRAINT UNQ_C14_TITLE_NAME UNIQUE (C14_TITLE_NAME)
);

CREATE TABLE T08_EMPLOYEE (
    C08_EMPLOYEE_ID INT AUTO_INCREMENT,
    C08_EMPLOYEE_NAME VARCHAR(255) NOT NULL,
    C08_EMPLOYEE_PHONE VARCHAR(20) NOT NULL,
    C08_EMPLOYEE_EMAIL VARCHAR(255) NOT NULL,
    C08_EMPLOYEE_GENDER TINYINT NOT NULL,
    C08_EMPLOYEE_DOB DATE NOT NULL,
    C08_TITLE_ID INT NOT NULL,
    C08_ACCOUNT_ID INT,
    PRIMARY KEY (C08_EMPLOYEE_ID),
    CONSTRAINT UNQ_C08_EMPLOYEE_PHONE UNIQUE (C08_EMPLOYEE_PHONE),
    CONSTRAINT UNQ_C08_EMPLOYEE_EMAIL UNIQUE (C08_EMPLOYEE_EMAIL),
    CONSTRAINT UNQ_C08_ACCOUNT_ID UNIQUE (C08_ACCOUNT_ID),
    CONSTRAINT FK_T08_T14 FOREIGN KEY (C08_TITLE_ID) REFERENCES T14_TITLE(C14_TITLE_ID),
    CONSTRAINT FK_T08_T09 FOREIGN KEY (C08_ACCOUNT_ID) REFERENCES T09_ACCOUNT(C09_ACCOUNT_ID) 
);

CREATE TABLE T07_CUSTOMER (
    C07_CUSTOMER_ID INT AUTO_INCREMENT,
    C07_CUSTOMER_NAME VARCHAR(255) NOT NULL,
    C07_CUSTOMER_PHONE VARCHAR(20) NOT NULL,
    C07_CUSTOMER_EMAIL VARCHAR(255) NOT NULL,
    C07_CUSTOMER_GENDER TINYINT NOT NULL, 
    C07_CUSTOMER_DOB DATE NOT NULL,
    C07_CUSTOMER_ADDRESS VARCHAR(255) NOT NULL,
    C07_ACCOUNT_ID INT,
    PRIMARY KEY (C07_CUSTOMER_ID),
    CONSTRAINT UNQ_C07_CUSTOMER_PHONE UNIQUE (C07_CUSTOMER_PHONE),
    CONSTRAINT UNQ_C07_CUSTOMER_EMAIL UNIQUE (C07_CUSTOMER_EMAIL),
    CONSTRAINT UNQ_C07_ACCOUNT_ID UNIQUE (C07_ACCOUNT_ID),
    CONSTRAINT FK_T07_T09 FOREIGN KEY (C07_ACCOUNT_ID) REFERENCES T09_ACCOUNT(C09_ACCOUNT_ID)
);



