CREATE TABLE T11_ORDER_STATUS (
    C11_ORDER_STATUS_ID INT AUTO_INCREMENT,
    C11_ORDER_STATUS_DESC VARCHAR(255) NOT NULL,
    PRIMARY KEY (C11_ORDER_STATUS_ID),
    CONSTRAINT UNQ_C11_ORDER_STATUS_DESC UNIQUE (C11_ORDER_STATUS_DESC)
);

CREATE TABLE T12_ORDER_STATUS_DETAIL (
    C12_ORDER_ID INT NOT NULL,
    C12_ORDER_STATUS_ID INT NOT NULL,
    C12_EMPLOYEE_ID INT NOT NULL,
    C12_LAST_UPDATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (C12_ORDER_ID, C12_ORDER_STATUS_ID, C12_LAST_UPDATED),
    CONSTRAINT FK_T12_T06 FOREIGN KEY (C12_ORDER_ID) REFERENCES T06_ORDER(C06_ORDER_ID),
    CONSTRAINT FK_T12_T11 FOREIGN KEY (C12_ORDER_STATUS_ID) REFERENCES T11_ORDER_STATUS(C11_ORDER_STATUS_ID),
    CONSTRAINT FK_T12_T08 FOREIGN KEY (C12_EMPLOYEE_ID) REFERENCES T08_EMPLOYEE(C08_EMPLOYEE_ID) 
);