-- java23-shopping dbp 07.sql
-- T17_ITEM_RECEIVED_NOTE, T18_ITEM_RECEIVED_NOTE_DETAIL, T19_PROVIDER

CREATE TABLE T17_ITEM_RECEIVED_NOTE(
	C17_IRN_ID INT AUTO_INCREMENT,
	C17_IRN_TIME DATETIME NOT NULL,
	C17_EMPLOYEE_ID INT NOT NULL,
    PRIMARY KEY(C17_IRN_ID),
    CONSTRAINT FK_17_08 FOREIGN KEY (C17_EMPLOYEE_ID) REFERENCES T08_EMPLOYEE(C08_EMPLOYEE_ID)
);
CREATE TABLE T18_ITEM_RECEIVED_NOTE_DETAIL (
  C18_IRN_ID INT,
  C18_ITEM_ID INT,
  C18_AMOUNT INT NOT NULL,
  C18_BUY_PRICE FLOAT NOT NULL,
  C18_PROVIDER_ID INT,
  PRIMARY KEY (C18_IRN_ID, C18_ITEM_ID),
  CONSTRAINT FK_18_17 FOREIGN KEY (C18_IRN_ID) REFERENCES T17_ITEM_RECEIVED_NOTE(C17_IRN_ID),
  CONSTRAINT FK_18_01 FOREIGN KEY (C18_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID),
  CONSTRAINT FK_18_19 FOREIGN KEY (C18_PROVIDER_ID) REFERENCES T19_PROVIDER(C19_PROVIDER_ID)
);
CREATE TABLE T19_PROVIDER (
     C19_PROVIDER_ID INT AUTO_INCREMENT,
     C19_PROVIDER_NAME VARCHAR(255) NOT NULL,
	 C19_PROVIDER_TAX INT NOT NULL,
     PRIMARY KEY(C19_PROVIDER_ID),
     CONSTRAINT UNQ_C19_PROVIDER_NAME UNIQUE(C19_PROVIDER_NAME)
);