-- T17_ITEM_RECEIVED_NOTE	T18_ITEM_RECEIVED_NOTE_DETAIL	T19_PROVIDER

CREATE TABLE T17_ITEM_RECEIVED_NOTE (
	C17_IRN_ID INT AUTO_INCREMENT PRIMARY KEY,
	C17_IRN_TIME DATETIME NOT NULL,
	C17_EMPLOYEE_ID INT NOT NULL,
    CONSTRAINT FK_T17_T08 FOREIGN KEY (C17_EMPLOYEE_ID) REFERENCES T08_EMPLOYEE (C08_EMPLOYEE_ID)
);

CREATE TABLE T19_PROVIDER (
	C19_PROVIDER_ID INT AUTO_INCREMENT PRIMARY KEY,
	C19_PROVIDER_NAME VARCHAR(100) NOT NULL,
	C19_PROVIDER_TAX VARCHAR(50) NOT NULL
);

CREATE TABLE T18_ITEM_RECEIVED_NOTE_DETAIL (
	C18_IRN_ID INT,
	C18_ITEM_ID INT,
	C18_AMOUNT INT,
	C18_BUY_PRICE INT,
	C18_PROVIDER_ID INT NOT NULL,
    PRIMARY KEY (C18_IRN_ID, C18_ITEM_ID),
    CONSTRAINT FK_T18_T19 FOREIGN KEY (C18_PROVIDER_ID) REFERENCES T19_PROVIDER (C19_PROVIDER_ID)
);