-- java23-shopping dbp 07.sql
-- T17_ITEM_RECEIVED_NOTE, T18_ITEM_RECEIVED_NOTE_DETAIL, T19_PROVIDE

-- T17_ITEM_RECEIVED_NOTE
DROP TABLE IF EXISTS T17_ITEM_RECEIVED_NOTE;
CREATE TABLE T17_ITEM_RECEIVED_NOTE (
    C17_IRN_ID INT AUTO_INCREMENT,
    C17_IRN_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    C17_EMPLOYEE_ID INT NOT NULL,
    PRIMARY KEY (C17_IRN_ID),
    CONSTRAINT FK_T17_T08 FOREIGN KEY(C17_EMPLOYEE_ID) REFERENCES T08_EMPLOYEE(C08_EMPLOYEE_ID)
);

-- T19_PROVIDER
DROP TABLE IF EXISTS T19_PROVIDER;
CREATE TABLE T19_PROVIDER (
    C19_PROVIDER_ID INT AUTO_INCREMENT,
    C19_PROVIDER_NAME VARCHAR(255) NOT NULL,
    C19_PROVIDER_TAX VARCHAR(20) NOT NULL,
    PRIMARY KEY (C19_PROVIDER_ID),
    CONSTRAINT UNQ_C19_PROVIDER_NAME UNIQUE (C19_PROVIDER_NAME),
    CONSTRAINT UNQ_C19_PROVIDER_TAX UNIQUE (C19_PROVIDER_TAX)
);

-- T18_ITEM_RECEIVED_NOTE_DETAIL
DROP TABLE IF EXISTS T18_ITEM_RECEIVED_NOTE_DETAIL;
CREATE TABLE T18_ITEM_RECEIVED_NOTE_DETAIL (
    C18_IRN_ID INT,
    C18_ITEM_ID INT,
    C18_AMOUNT INT NOT NULL,
    C18_BUY_PRICE DECIMAL(10,2),
    C18_PROVIDER_ID INT NOT NULL,
    PRIMARY KEY (C18_IRN_ID, C18_ITEM_ID),
    CONSTRAINT FK_T18_T17 FOREIGN KEY (C18_IRN_ID) REFERENCES T17_ITEM_RECEIVED_NOTE (C17_IRN_ID),
    CONSTRAINT FK_T18_T01 FOREIGN KEY (C18_ITEM_ID) REFERENCES T01_ITEM (C01_ITEM_ID),
    CONSTRAINT FK_T18_T19 FOREIGN KEY (C18_PROVIDER_ID) REFERENCES T19_PROVIDER (C19_PROVIDER_ID),
    CONSTRAINT CHK_C18_AMOUNT CHECK (C18_AMOUNT > 0),
    CONSTRAINT CHK_C18_BUY_PRICE CHECK (C18_BUY_PRICE > 0)
);