-- Create table for N-N demo (no extra columns)
DROP TABLE IF EXISTS T21_POST;
CREATE TABLE T21_POST(
	C21_POST_ID INT AUTO_INCREMENT,
    C21_POST_TITLE VARCHAR(255) NOT NULL,
    PRIMARY KEY (C21_POST_ID)
);

DROP TABLE IF EXISTS T22_TAG;
CREATE TABLE T22_TAG (
	C22_TAG_ID INT AUTO_INCREMENT,
    C22_TAG_NAME VARCHAR(255) NOT NULL, 
    PRIMARY KEY (C22_TAG_ID)
);

DROP TABLE IF EXISTS T23_POST_TAG;
CREATE TABLE T23_POST_TAG(
	C23_POST_ID INT,
    C23_TAG_ID INT,
    PRIMARY KEY (C23_POST_ID, C23_TAG_ID),
    CONSTRAINT FK_T23_T21_POST FOREIGN KEY (C23_POST_ID) REFERENCES T21_POST(C21_POST_ID),
    CONSTRAINT FK_T23_T22_TAG FOREIGN KEY (C23_TAG_ID) REFERENCES T22_TAG(C22_TAG_ID)
);