-- java23-shopping dbp 03.sql
-- C09_ACCOUNT_ID	C10_ROLE_ID

CREATE TABLE T10_ROLE(
	C10_ROLE_ID INT AUTO_INCREMENT,
	C10_ROLE_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (C10_ROLE_ID),
    CONSTRAINT UNQ_C10_ROLE_NAME UNIQUE(C10_ROLE_NAME)
);

CREATE TABLE T09_ACCOUNT(
	C09_ACCOUNT_ID INT AUTO_INCREMENT,
	C09_USERNAME VARCHAR(255) NOT NULL,
	C09_PASSWORD VARCHAR(255) NOT NULL,
	C09_ACCOUNT_STATUS BIT(1) NOT NULL,
	C09_ROLE_ID INT NOT NULL,
    PRIMARY KEY (C09_ACCOUNT_ID),
    CONSTRAINT FK_T09_T10 FOREIGN KEY (C09_ROLE_ID) REFERENCES T10_ROLE(C10_ROLE_ID),
    CONSTRAINT UNQ_C09_USERNAME UNIQUE(C09_USERNAME)
);

