-- -- T09_ACCOUNT,	T10_ROLE

DROP TABLE IF EXISTS T10_ROLE;
CREATE TABLE T10_ROLE (
	C10_ROLE_ID INT AUTO_INCREMENT PRIMARY KEY,
	C10_ROLE_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT UNQ_C10_ROLE_NAME UNIQUE(C10_ROLE_NAME)
);

DROP TABLE IF EXISTS T09_ACCOUNT;
CREATE TABLE T09_ACCOUNT (
	C09_ACCOUNT_ID INT AUTO_INCREMENT PRIMARY KEY,
	C09_USERNAME VARCHAR(50) NOT NULL,
	C09_PASSWORD TEXT NOT NULL,
	C09_ACCOUNT_STATUS BIT(1) NOT NULL,
	C09_ROLE_ID INT NOT NULL,
    CONSTRAINT UNQ_C09_USERNAME UNIQUE(C09_USERNAME),
    CONSTRAINT FK_T09_T10 FOREIGN KEY (C09_ROLE_ID) REFERENCES T10_ROLE (C10_ROLE_ID)
);