-- T14_TITLE, T08_EMPLOYEE, T07_CUSTOMER

CREATE TABLE T14_TITLE (
	C14_TITLE_ID INT AUTO_INCREMENT PRIMARY KEY,
	C14_TITLE_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE T08_EMPLOYEE (
	C08_EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
	C08_EMPLOYEE_NAME VARCHAR(100) NOT NULL,
	C08_EMPLOYEE_PHONE VARCHAR(50),
	C08_EMPLOYEE_EMAIL VARCHAR(50),
	C08_EMPLOYEE_GENDER BIT(1) NOT NULL,
	C08_EMPLOYEE_DOB VARCHAR(20) NOT NULL,
	C08_TITLE_ID INT NOT NULL,
	C08_ACCOUNT_ID INT NOT NULL,
    CONSTRAINT FK_T08_T14_1 FOREIGN KEY (C08_TITLE_ID) REFERENCES T14_TITLE (C14_TITLE_ID),
    CONSTRAINT FK_T08_T14_2 FOREIGN KEY (C08_ACCOUNT_ID) REFERENCES T09_ACCOUNT (C09_ACCOUNT_ID)
);

CREATE TABLE T07_CUSTOMER (
	C07_CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
	C07_CUSTOMER_NAME VARCHAR(70) NOT NULL,
	C07_CUSTOMER_PHONE VARCHAR(50),
	C07_CUSTOMER_EMAIL VARCHAR(50),
	C07_CUSTOMER_GENDER BIT(1) NOT NULL,
	C07_CUSTOMER_DOB VARCHAR(20) NOT NULL,
	C07_CUSTOMER_ADDRESS VARCHAR(255) NOT NULL,
	C07_ACCOUNT_ID INT NOT NULL,
    CONSTRAINT FK_T07_T09 FOREIGN KEY (C07_ACCOUNT_ID) REFERENCES T09_ACCOUNT (C09_ACCOUNT_ID)
);