-- java23-shopping dbp 04.sql
-- T14_TITLE, T08_EMPLOYEE, T07_CUSTOMER

-- T14_TITLE
CREATE TABLE T14_TITLE (
	C14_TITLE_ID INT AUTO_INCREMENT,
	C14_TITLE_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY(C14_TITLE_ID),
    CONSTRAINT UNQ_C14_TITLE_NAME UNIQUE(C14_TITLE_NAME)
);

-- T08_EMPLOYEE
CREATE TABLE T08_EMPLOYEE(
	C08_EMPLOYEE_ID INT AUTO_INCREMENT,
	C08_EMPLOYEE_NAME VARCHAR(255) NOT NULL,
	C08_EMPLOYEE_PHONE CHAR(10) NOT NULL,
	C08_EMPLOYEE_EMAIL VARCHAR(50) NOT NULL,
	C08_EMPLOYEE_GENDER BIT(1) NOT NULL,
	C08_EMPLOYEE_DOB DATE NOT NULL,
	C08_TITLE_ID INT NOT NULL,
	C08_ACCOUNT_ID INT NOT NULL,
    PRIMARY KEY(C08_EMPLOYEE_ID),
    CONSTRAINT FK_C08_C14 FOREIGN KEY(C08_TITLE_ID) REFERENCES T14_TITLE(C14_TITLE_ID),
    CONSTRAINT FK_C08_C09 FOREIGN KEY(C08_ACCOUNT_ID) REFERENCES T09_ACCOUNT(C09_ACCOUNT_ID),
    CONSTRAINT UNQ_C08_PHONE_EMAIL UNIQUE(C08_EMPLOYEE_PHONE, C08_EMPLOYEE_EMAIL),
    CONSTRAINT CK_C08_EMPLOYEE_PHONE CHECK(C08_EMPLOYEE_PHONE REGEXP '^0[0-9]{9}$'),
    CONSTRAINT CK_C08_EMPLOYEE_EMAIL CHECK (C08_EMPLOYEE_EMAIL REGEXP '^[a-zA-Z0-9][a-zA-Z0-9._%+-]*@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')
);

-- T07_CUSTOMER
CREATE TABLE T07_CUSTOMER (
	C07_CUSTOMER_ID INT AUTO_INCREMENT,
	C07_CUSTOMER_NAME VARCHAR(255) NOT NULL,
	C07_CUSTOMER_PHONE CHAR(10) NOT NULL,
	C07_CUSTOMER_EMAIL VARCHAR(50) NOT NULL,
	C07_CUSTOMER_GENDER BIT(1) NOT NULL,
	C07_CUSTOMER_DOB DATE,
	C07_CUSTOMER_ADDRESS TEXT NOT NULL,
	C07_ACCOUNT_ID INT NOT NULL,
    PRIMARY KEY(C07_CUSTOMER_ID),
    CONSTRAINT FK_C07_C09 FOREIGN KEY(C07_ACCOUNT_ID) REFERENCES T09_ACCOUNT(C09_ACCOUNT_ID),
    CONSTRAINT UNQ_C07_PHONE_EMAIL UNIQUE(C07_CUSTOMER_PHONE, C07_CUSTOMER_EMAIL),
    CONSTRAINT CK_C07_CUSTOMER_PHONE CHECK(C07_CUSTOMER_PHONE REGEXP '^0[0-9]{9}$'),
    CONSTRAINT CK_C07_CUSTOMER_EMAIL CHECK (C07_CUSTOMER_EMAIL REGEXP '^[a-zA-Z0-9][a-zA-Z0-9._%+-]*@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')
);

