-- java23-shopping dbp 05.sql
-- T13_PAYMENT_METHOD, T06_ORDER, T15_BILL, T16_ORDER_DETAIL

CREATE TABLE T13_PAYMENT_METHOD(
  C13_PAYMENT_METHOD_ID INT AUTO_INCREMENT,
  C13_PAYMENT_METHOD_NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY(C13_PAYMENT_METHOD_ID)
);

CREATE TABLE T06_ORDER(
  C06_ORDER_ID INT AUTO_INCREMENT,
  C06_RECEIVER_NAME VARCHAR(255) NOT NULL,
  C06_RECEIVER_PHONE INT NOT NULL,
  C06_DELIVERY_ADDRESS VARCHAR(255) NOT NULL,
  C06_CUSTOMER_ID INT NOT NULL,
  C06_ORDER_TIME DATETIME,
  C06_PAYMENT_METHOD_ID INT,
  C06_EMPLOYEE_ID INT NOT NULL,
  CONSTRAINT FK_06_08 FOREIGN KEY (C06_EMPLOYEE_ID) REFERENCES T08_EMPLOYEE(C08_EMPLOYEE_ID),
  CONSTRAINT FK_T06_T07 FOREIGN KEY (C06_CUSTOMER_ID) REFERENCES T07_CUSTOMER(C07_CUSTOMER_ID)
);

CREATE TABLE T15_BILL(
  C15_BILL_ID INT AUTO_INCREMENT,
  C15_DELIVERY_FEE FLOAT NOT NULL,
  C15_TOTAL_OF_MONEY FLOAT NOT NULL,
  C15_ORDER_ID INT NOT NULL,
  PRIMARY KEY(C15_BILL_ID),
  CONSTRAINT FK_T15_T06 FOREIGN KEY (C15_ORDER_ID) REFERENCES T06_ORDER(C06_ORDER_ID)
);

CREATE TABLE T16_ORDER_DETAIL(
  C16_ORDER_ID INT NOT NULL,
  C16_ITEM_DETAIL_ID INT NOT NUll,
  C16_AMOUNT INT NOT NULL,
  PRIMARY KEY (C16_ORDER_ID, C16_ITEM_DETAIL_ID),
  CONSTRAINT FK_T16_T06 FOREIGN KEY (C16_ORDER_ID) REFERENCES T06_ORDER(C06_ORDER_ID)
);
