-- java23-shopping dbp 05.sql
-- C06_ORDER_ID C13_PAYMENT_METHOD_ID	C15_BILL_ID	C16_ORDER_ID

CREATE TABLE T13_PAYMENT_METHOD(
	C13_PAYMENT_METHOD_ID INT AUTO_INCREMENT PRIMARY KEY,
	C13_PAYMENT_METHOD_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT UNQ_C13_PAYMENT_METHOD_NAME UNIQUE(C13_PAYMENT_METHOD_NAME),
    CONSTRAINT C13_PAYMENT_METHOD_NAME_CHECK 
		CHECK (C13_PAYMENT_METHOD_NAME 
			IN ('Cash on Delivery','Online Payment - Bank Transfer','Online Payment - Debit Card'))
);

CREATE TABLE T06_ORDER(
	C06_ORDER_ID INT AUTO_INCREMENT,
	C06_RECEIVER_NAME VARCHAR(255) NOT NULL,
	C06_RECEIVER_PHONE VARCHAR(15) NOT NULL,
	C06_DELIVERY_ADDRESS TEXT NOT NULL,
	C06_CUSTOMER_ID INT NOT NULL,
	C06_ORDER_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	C06_PAYMENT_METHOD_ID INT NOT NULL,
	C06_EMPLOYEE_ID INT NOT NULL,
    PRIMARY KEY (C06_ORDER_ID),
    CONSTRAINT FK_T06_T07 FOREIGN KEY (C06_CUSTOMER_ID) REFERENCES T07_CUSTOMER(C07_CUSTOMER_ID),
	CONSTRAINT FK_T06_T13 FOREIGN KEY (C06_PAYMENT_METHOD_ID) REFERENCES T13_PAYMENT_METHOD(C13_PAYMENT_METHOD_ID),
	CONSTRAINT FK_T06_T08 FOREIGN KEY (C06_EMPLOYEE_ID) REFERENCES T08_EMPLOYEE(C08_EMPLOYEE_ID)
);


CREATE TABLE T15_BILL(
	C15_BILL_ID INT AUTO_INCREMENT,
	C15_DELIVERY_FEE FLOAT NOT NULL DEFAULT 0,
	C15_TOTAL_OF_MONEY FLOAT NOT NULL DEFAULT 0,
	C15_ORDER_ID INT NOT NULL,
    PRIMARY KEY (C06_ORDER_ID),
    CONSTRAINT FK_T15_T06 FOREIGN KEY (C15_ORDER_ID) REFERENCES T06_ORDER(C06_ORDER_ID),
    CONSTRAINT UNQ_C15_ORDER UNIQUE(C15_ORDER_ID),
    CONSTRAINT C15_DELIVERY_FEE_CHECK CHECK (C15_DELIVERY_FEE >= 0),
    CONSTRAINT C15_TOTAL_OF_MONEY_CHECK CHECK (C15_TOTAL_OF_MONEY >= 0)
);
