-- java23-shopping dbp 06.sql
-- T11_ORDER_STATUS, T12_ORDER_STATUS_DETAIL

CREATE TABLE T11_ORDER_STATUS (
    C11_ORDER_STATUS_ID INT AUTO_INCREMENT,
    C11_ORDER_STATUS_DESC VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (C11_ORDER_STATUS_ID)
);

CREATE TABLE T12_ORDER_STATUS_DETAIL (
    C12_ORDER_ID INT,
    C12_ORDER_STATUS_ID INT,
    C12_EMPLOYEE_ID INT NOT NULL,
    C12_LAST_UPDATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (C12_ORDER_ID, C12_ORDER_STATUS_ID),
    CONSTRAINT FK_C12_C06 FOREIGN KEY (C12_ORDER_ID) REFERENCES T06_ORDER(C06_ORDER_ID),
    CONSTRAINT FK_C12_C11 FOREIGN KEY (C12_ORDER_STATUS_ID) REFERENCES T11_ORDER_STATUS(C11_ORDER_STATUS_ID),
    CONSTRAINT FK_C12_C08 FOREIGN KEY (C12_EMPLOYEE_ID) REFERENCES T08_EMPLOYEE(C08_EMPLOYEE_ID)
);
