-- T11_ORDER_STATUS, T12_ORDER_STATUS_DETAIL

CREATE TABLE T11_ORDER_STATUS (
	C11_ORDER_STATUS_ID INT AUTO_INCREMENT PRIMARY KEY,
	C11_ORDER_STATUS_DESC BIT(6) NOT NULL
);

CREATE TABLE T12_ORDER_STATUS_DETAIL (
	C12_ORDER_ID INT NOT NULL,
	C12_ORDER_STATUS_ID INT NOT NULL,
	C12_EMPLOYEE_ID INT NOT NULL,
	C12_LAST_UPDATED DATETIME NOT NULL
);