-- Add REF_ITEM_ID column to T01_ITEM
ALTER TABLE t01_item ADD COLUMN C01_REF_ITEM_ID INT;
ALTER TABLE t01_item ADD CONSTRAINT FK_REF_ITEM FOREIGN KEY (C01_REF_ITEM_ID) REFERENCES t01_item(C01_ITEM_ID);