ALTER TABLE `java23_shopping`.`t07_customer` 
CHANGE COLUMN `C07_CUSTOMER_PHONE` `C07_CUSTOMER_PHONE` VARCHAR(50) NULL ,
CHANGE COLUMN `C07_CUSTOMER_GENDER` `C07_CUSTOMER_GENDER` BIT(1) NULL ,
CHANGE COLUMN `C07_CUSTOMER_ADDRESS` `C07_CUSTOMER_ADDRESS` TEXT NULL ;
