-- Create table T23_POST, T24_POST_TAG, T25_TAG

DROP TABLE T24_POST_TAG;
DROP TABLE T23_POST;
DROP TABLE T25_TAG;


CREATE TABLE T23_POST (
	C23_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    C23_TITLE VARCHAR(255) NOT NULL
);

CREATE TABLE T25_TAG (
	C25_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    C25_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE T24_POST_TAG (
	C24_POST_ID INT NOT NULL,
    C24_TAG_ID INT NOT NULL,
    PRIMARY KEY (C24_POST_ID, C24_TAG_ID),
    CONSTRAINT FK_T24_T23 FOREIGN KEY (C24_POST_ID) REFERENCES T23_POST(C23_ID),
    CONSTRAINT FK_T24_T25 FOREIGN KEY (C24_TAG_ID) REFERENCES T25_TAG(C25_ID)
);