-- java23-shopping dbp 04.sql
-- T14_TITLE, T08_EMPLOYEE, T07_CUSTOMER

CREATE TABLE T14_TITLE (
	C14_TITLE_ID INT AUTO_INCREMENT PRIMARY KEY,
	C14_TITLE_NAME VARCHAR(255) NOT NULL,
	CONSTRAINT UNQ_C14_TITLE_NAME UNIQUE(C14_TITLE_NAME)
);


CREATE TABLE T08_EMPLOYEE (
	C08_EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
	C08_EMPLOYEE_NAME VARCHAR(255) NOT NULL,
	C08_EMPLOYEE_PHONE VARCHAR(255) NOT NULL,
	C08_EMPLOYEE_EMAIL VARCHAR(255) NOT NULL,
	C08_EMPLOYEE_GENDER BIT(1) NOT NULL,
	C08_EMPLOYEE_DOB DATE NOT NULL,
	C08_TITLE_ID INT,
	C08_ACCOUNT_ID INT,
	CONSTRAINT UNQ_C08_EMPLOYEE_PHONE_EMAIL UNIQUE(C08_EMPLOYEE_PHONE, C08_EMPLOYEE_EMAIL),
	CONSTRAINT FK_T08_T14 FOREIGN KEY (C08_TITLE_ID) REFERENCES T14_TITLE(C14_TITLE_ID),
	CONSTRAINT FK_T08_T09 FOREIGN KEY (C08_ACCOUNT_ID) REFERENCES T09_ACCOUNT(C09_ACCOUNT_ID)
);
CREATE TABLE T07_CUSTOMER (
	C07_CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
	C07_CUSTOMER_NAME VARCHAR(255) NOT NULL,
	C07_CUSTOMER_PHONE INT NOT NULL,
	C07_CUSTOMER_EMAIL VARCHAR(255) NOT NULL,
	C07_CUSTOMER_GENDER BIT(1) NOT NULL,
	C07_CUSTOMER_DOB DATE NOT NULL,
	C07_CUSTOMER_ADDRESS VARCHAR(255) NOT NULL,
	C07_ACCOUNT_ID INT,
	CONSTRAINT UNQ_C07_CUSTOMER_PHONE_EMAIL UNIQUE(C07_CUSTOMER_PHONE, C07_CUSTOMER_EMAIL),
	CONSTRAINT FK_T07_T09 FOREIGN KEY (C07_ACCOUNT_ID) REFERENCES T09_ACCOUNT(C09_ACCOUNT_ID)
);