-- java23-shopping dbp 05.sql
-- T13_PAYMENT_METHOD, T06_ORDER, T15_BILL, T16_ITEM_DETAIL

CREATE TABLE T13_PAYMENT_METHOD(
	C13_PAYMENT_METHOD_ID INT AUTO_INCREMENT,
    C13_PAYMENT_METHOD_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (C13_PAYMENT_METHOD_ID),
    CONSTRAINT UNQ_C13_PAYMENT_METHOD_NAME UNIQUE(C13_PAYMENT_METHOD_NAME)
);

CREATE TABLE T06_ORDER(
	C06_ORDER_ID INT AUTO_INCREMENT,
	C06_RECEIVER_NAME VARCHAR(255) NOT NULL,
	C06_RECEIVER_PHONE VARCHAR(10) NOT NULL,
	C06_DELIVERY_ADDRESS VARCHAR(255) NOT NULL,
	C06_CUSTOMER_ID INT NOT NULL,
	C06_ORDER_TIME DATETIME NOT NULL,
	C06_PAYMENT_METHOD_ID INT NOT NULL,
	C06_EMPLOYEE_ID INT NOT NULL,
    PRIMARY KEY (C06_ORDER_ID),
    CONSTRAINT FK_T06_T13 FOREIGN KEY (C06_PAYMENT_METHOD_ID) REFERENCES T13_PAYMENT_METHOD(C13_PAYMENT_METHOD_ID),
    CONSTRAINT FK_T06_T07 FOREIGN KEY (C06_CUSTOMER_ID) REFERENCES T07_CUSTOMER(C07_CUSTOMER_ID),
    CONSTRAINT FK_T06_T08 FOREIGN KEY (C06_EMPLOYEE_ID) REFERENCES T08_EMPLOYEE(C08_EMPLOYEE_ID),
    CONSTRAINT UNQ_C06_RECEIVER_PHONE UNIQUE (C06_RECEIVER_PHONE)
);

CREATE TABLE T15_BILL(
	C15_BILL_ID INT AUTO_INCREMENT,
    C15_DELIVERY_FEE DECIMAL(10, 2) DEFAULT 0,
    C15_TOTAL_OF_MONEY DECIMAL(10, 2) NOT NULL,
    C15_ORDER_ID INT NOT NULL,
    PRIMARY KEY (C15_BILL_ID),
	CONSTRAINT FK_T15_T06 FOREIGN KEY (C15_ORDER_ID) REFERENCES T06_ORDER(C06_ORDER_ID)
);

CREATE TABLE T16_ITEM_DETAIL(
	C16_ORDER_ID INT NOT NULL,
    C16_ITEM_DETAIL_ID INT NOT NULL,
    C16_AMOUNT INT NOT NULL,
    PRIMARY KEY (C16_ORDER_ID, C16_ITEM_DETAIL_ID),
    CONSTRAINT FK_T16_T06 FOREIGN KEY (C16_ORDER_ID) REFERENCES T06_ORDER(C06_ORDER_ID),
    CONSTRAINT FK_T16_T03 FOREIGN KEY (C16_ITEM_DETAIL_ID) REFERENCES T03_ITEM_DETAIL(C03_ITEM_DETAIL_ID)
)