SELECT * FROM T04_ITEM_GROUP;

-- param: X' OR '1=1
SELECT * FROM T04_ITEM_GROUP WHERE C04_ITEM_GROUP_NAME = 'X' OR '1=1';

SELECT * FROM T04_ITEM_GROUP WHERE C04_ITEM_GROUP_ID = 5;

SELECT * FROM T04_ITEM_GROUP WHERE C04_ITEM_GROUP_NAME = 'Mũ';

INSERT INTO T04_ITEM_GROUP(C04_ITEM_GROUP_ID, C04_ITEM_GROUP_NAME)
VALUES(?, ?);

SELECT t01.C01_ITEM_ID ITEM_ID,
	   t01.C01_ITEM_NAME ITEM_NAME,
       t01.C01_ITEM_GROUP_ID ITEM_GROUP_ID,
       t04.C04_ITEM_GROUP_NAME ITEM_GROUP_NAME
  FROM T01_ITEM t01
  JOIN T04_ITEM_GROUP t04
    ON t01.C01_ITEM_GROUP_ID = t04.C04_ITEM_GROUP_ID;
    
-- Đếm số lượng mặt hàng trong từng loại hàng
SELECT t04.C04_ITEM_GROUP_ID ITEM_GROUP_ID,
       t04.C04_ITEM_GROUP_NAME ITEM_GROUP_NAME,
       COUNT(*) AMOUNT_OF_ITEMS
  FROM T01_ITEM t01
  JOIN T04_ITEM_GROUP t04
    ON t01.C01_ITEM_GROUP_ID = t04.C04_ITEM_GROUP_ID
  GROUP BY t04.C04_ITEM_GROUP_ID;
  
SELECT * FROM t01_item;  

SELECT * FROM java23_shopping.t06_order;

SELECT DISTINCT cast(C06_ORDER_TIME AS DATE) ORDER_DATE FROM T06_ORDER;

SELECT * FROM T07_CUSTOMER;

INSERT INTO T07_CUSTOMER(C07_CUSTOMER_NAME, C07_USERNAME, C07_PASSWORD, C07_ACCOUNT_STATUS)
VALUE(?, ?, ?, ?);

SELECT * FROM t04_item_group ORDER BY C04_ITEM_GROUP_ID;

SET AUTOCOMMIT = 0;
SET AUTOCOMMIT = 1;
ROLLBACK;
COMMIT;

CALL mergeItemGroup(16, "Loại Hàng 16");

DELETE FROM t04_item_group WHERE C04_ITEM_GROUP_ID = 12;

SELECT * FROM t03_item_detail;

-- 1: 125
-- 2: 125